server:
  port: 443
  servlet:
    context-path: /
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: abc123
    trust-store: classpath:truststore.p12
    trust-store-password: abc123
    trust-store-type: PKCS12



#server:
#  port: 443
#  servlet:
#    context-path: /
#  ssl:
#    enabled: true
#    key-store: classpath:localp12.p12
#    key-store-type: PKCS12
#    key-password: abc123
#    key-store-password: abc123

#server:
#  port: 443
#  servlet:
#    context-path: /
#  ssl:
#    enabled: true
#    key-alias: local_ssl
#    key-store: classpath:local-ssl.p12
#    key-store-type: PKCS12
#    key-password: abc123
#    key-store-password: abc123

#server:
#  port: 443
#  servlet:
#    context-path: /
#  ssl:
#    enabled: true
#    key-alias: localhost_ssl
#    key-store: classpath:server.jks
#    key-store-type: jks
#    key-password: secret
#    key-store-password: secret